In [1]:
import polars as pl
from pathlib import Path

In [2]:
ad_analysis_raw = pl.read_csv(Path('../data/01_bronze/notion_ficha_analise.csv'))

In [3]:
ad_analysis_raw

shape: (152, 39)
┌────────────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬──────┐
│ Identifica ┆ Alinhament ┆ Autorizaçõ ┆ Comerciali ┆ … ┆ Tipo de   ┆ Variação  ┆ Variação  ┆ form │
│ dor        ┆ o          ┆ es         ┆ zação      ┆   ┆ produto   ┆ tipográfi ┆ typeface  ┆ ---  │
│ ---        ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ---       ┆ ca        ┆ ---       ┆ i64  │
│ str        ┆ str        ┆ str        ┆ str        ┆   ┆ str       ┆ ---       ┆ str       ┆      │
│            ┆            ┆            ┆            ┆   ┆           ┆ str       ┆           ┆      │
╞════════════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪══════╡
│ oleo_figad ┆ Centraliza ┆ Ausente    ┆ Vende-se   ┆ … ┆ Oleo      ┆ Bold,     ┆ Serifa    ┆ 1    │
│ o_bacalhau ┆ do, Justif ┆            ┆ em todas   ┆   ┆           ┆ Caixa     ┆           ┆      │
│            ┆ icado      ┆            ┆ as         ┆   ┆           ┆ alta,     ┆           ┆      │
│            ┆ esqu…      ┆            ┆ pharmacia… ┆   ┆           ┆ Regular,  ┆           ┆      │
│            ┆            ┆            ┆            ┆   ┆           ┆ Ver…      ┆           ┆      │
│ tonico_ori ┆ Centraliza ┆ Ausente    ┆ Vende-se   ┆ … ┆ Tonico    ┆ Bold,     ┆ Serifa    ┆ 1    │
│ ental_cabe ┆ do, Justif ┆            ┆ em todas   ┆   ┆           ┆ Caixa     ┆           ┆      │
│ llo        ┆ icado      ┆            ┆ as         ┆   ┆           ┆ alta,     ┆           ┆      │
│            ┆ esqu…      ┆            ┆ pharmacia… ┆   ┆           ┆ Regular   ┆           ┆      │
│ pilulas_ve ┆ Centraliza ┆ Ausente    ┆ Vende-se   ┆ … ┆ Pilula    ┆ Bold,     ┆ Serifa    ┆ 1    │
│ geates_ass ┆ do, Justif ┆            ┆ em todas   ┆   ┆           ┆ Caixa     ┆           ┆      │
│ ucaradas_b ┆ icado      ┆            ┆ as         ┆   ┆           ┆ alta,     ┆           ┆      │
│ …          ┆ esqu…      ┆            ┆ farmácias… ┆   ┆           ┆ Regular,  ┆           ┆      │
│            ┆            ┆            ┆            ┆   ┆           ┆ Ver…      ┆           ┆      │
│ og_novo_de ┆ Centraliza ┆ Ausente    ┆ -          ┆ … ┆ Elexir/el ┆ Bold,     ┆ Serifa    ┆ 1    │
│ purativo_e ┆ do, Justif ┆            ┆            ┆   ┆ ixir,     ┆ Caixa     ┆           ┆      │
│ xtracto_sa ┆ icado      ┆            ┆            ┆   ┆ Extrato   ┆ alta,     ┆           ┆      │
│ …          ┆ esqu…      ┆            ┆            ┆   ┆           ┆ Itálico,  ┆           ┆      │
│            ┆            ┆            ┆            ┆   ┆           ┆ Reg…      ┆           ┆      │
│ salsaparri ┆ Centraliza ┆ Ausente    ┆ Vende-se   ┆ … ┆ Indefinid ┆ Caixa     ┆ Serifa    ┆ 1    │
│ lha_bristo ┆ do, Justif ┆            ┆ em todas   ┆   ┆ o         ┆ alta,     ┆           ┆      │
│ l          ┆ icado      ┆            ┆ as         ┆   ┆           ┆ Regular   ┆           ┆      │
│            ┆ esqu…      ┆            ┆ pharmacia… ┆   ┆           ┆           ┆           ┆      │
│ …          ┆ …          ┆ …          ┆ …          ┆ … ┆ …         ┆ …         ┆ …         ┆ …    │
│ pilulas_ve ┆ Centraliza ┆ Ausente    ┆ Pharmacia  ┆ … ┆ Pilula    ┆ Bold,     ┆ Sem       ┆ 1    │
│ rmifugas_d ┆ do, Justif ┆            ┆ Ezequiel   ┆   ┆           ┆ Caixa     ┆ serifa,   ┆      │
│ r_oliveira ┆ icado      ┆            ┆ 70 - Rua   ┆   ┆           ┆ alta,     ┆ Serifa    ┆      │
│            ┆ esqu…      ┆            ┆ do…        ┆   ┆           ┆ Regular,  ┆           ┆      │
│            ┆            ┆            ┆            ┆   ┆           ┆ Ver…      ┆           ┆      │
│ elixir_cab ┆ Centraliza ┆ Ausente    ┆ Continua a ┆ … ┆ Elexir/el ┆ Bold,     ┆ Serifa    ┆ 1    │
│ oclo       ┆ do, Justif ┆            ┆ ver        ┆   ┆ ixir      ┆ Regular   ┆           ┆      │
│            ┆ icado      ┆            ┆ vendido na ┆   ┆           ┆           ┆           ┆      │
│            ┆ esqu…      ┆            ┆ chác…      ┆   ┆           ┆           ┆           ┆      │
│ grageas_de ┆ Centraliza ┆ Ausente    ┆ -          ┆ … ┆ Gragea    ┆ Bold,     ┆ Serifa    ┆ 1    │
│ purativas_ ┆ do         ┆            ┆            ┆   ┆           ┆ Itálico,  ┆           ┆      │
│ maior      ┆            ┆            ┆            ┆   ┆           ┆ Regular   ┆           ┆      │
│ licor_cent ┆ Centraliza ┆ Ausente    ┆ -          ┆ … ┆ Licor     ┆ Bold,     ┆ Fantasia, ┆ 1    │
│ aurea_2    ┆ do         ┆            ┆            ┆   ┆           ┆ Caixa     ┆ Serifa    ┆      │
│            ┆            ┆            ┆            ┆   ┆           ┆ alta,     ┆           ┆      │
│            ┆            ┆            ┆            ┆   ┆           ┆ Itálico,  ┆           ┆      │
│            ┆            ┆            ┆            ┆   ┆           ┆ Reg…      ┆           ┆      │
│ licor_cent ┆ Centraliza ┆ Ausente    ┆ -          ┆ … ┆ Licor     ┆ Bold,     ┆ Fantasia, ┆ 1    │
│ aurea_3    ┆ do, Justif ┆            ┆            ┆   ┆           ┆ Caixa     ┆ Serifa    ┆      │
│            ┆ icado      ┆            ┆            ┆   ┆           ┆ alta,     ┆           ┆      │
│            ┆ esqu…      ┆            ┆            ┆   ┆           ┆ Itálico,  ┆           ┆      │
│            ┆            ┆            ┆            ┆   ┆           ┆ Reg…      ┆           ┆      │
└────────────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴──────┘

In [4]:
schema_analysis_sheet = [
  # a. Identificação do objeto 
 'Identificador',
 'ID',
 'Link',
    
 'Produto ofertado (título completo)',
 'Primeiras palavras do anúncio',
 'Doença mencionada',
 'Tipo de produto',
 'Substâncias',
 'Extras',
    
 # b. Indentificação do contexto
 'Informações indicativas',
 'Menções a lugares',
 'Origem',
 'Preço',
 'Responsável técnico',
 'Comercialização',
 'Depósito',
 'Produção',
    
  # c. Identificação do discurso
 'Palavra-chave efeito',
 'Palavras-chave produto',
 'Discursos de autoridade',
 'Público mencionado',
 'Detalhamento do efeito',
 'Detalhamento forma de uso',
 'Autorizações',
 'Observações',


 # d. Identificação gráfica
 'Sinal visual de autoridade',
 'Quantidade de variações tipográficas (aprox.)',
 'Variação typeface',
 'Variação tipográfica',
 'Alinhamento',
 'Diagramação',
 'Hieraquia da informação',
 'Tipificação da imagem (aprox.)',
 'Elementos de composição',

 #   
 'Original (primeira aparição)',
 'Derivados',
 
 'Status',
 'Dúvidas',
]

multi_select_columns = [
 'Primeiras palavras do anúncio',
 'Doença mencionada',
 'Tipo de produto',
 'Substâncias',
 'Extras',
    
 # b. Indentificação do contexto
 'Informações indicativas',
 'Menções a lugares',
 'Origem',
 'Responsável técnico',
    
  # c. Identificação do discurso
 'Palavra-chave efeito',
 'Palavras-chave produto',
 'Discursos de autoridade',
 'Público mencionado',
 'Detalhamento do efeito',
 'Detalhamento forma de uso',
 'Autorizações',

 # d. Identificação gráfica
 'Sinal visual de autoridade',
 'Variação typeface',
 'Variação tipográfica',
 'Alinhamento',
 'Diagramação',
 'Hieraquia da informação',
 'Tipificação da imagem (aprox.)',
 'Elementos de composição',
]

single_value_columns = [col for col in schema_analysis_sheet if col not in multi_select_columns]

In [5]:
ad_analysis = (ad_analysis_raw
    .select([
        pl.col(c).str.split(", ").alias(c) if c in multi_select_columns else pl.col(c)
        for c in schema_analysis_sheet])
    .filter(pl.col('Status').is_in(['Finalizado', 'Revisado']))
    )
ad_analysis

shape: (152, 38)
┌─────────────┬─────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬─────────┐
│ Identificad ┆ ID  ┆ Link       ┆ Produto    ┆ … ┆ Original   ┆ Derivados  ┆ Status     ┆ Dúvidas │
│ or          ┆ --- ┆ ---        ┆ ofertado   ┆   ┆ (primeira  ┆ ---        ┆ ---        ┆ ---     │
│ ---         ┆ i64 ┆ str        ┆ (título    ┆   ┆ aparição)  ┆ str        ┆ str        ┆ str     │
│ str         ┆     ┆            ┆ compl…     ┆   ┆ ---        ┆            ┆            ┆         │
│             ┆     ┆            ┆ ---        ┆   ┆ str        ┆            ┆            ┆         │
│             ┆     ┆            ┆ str        ┆   ┆            ┆            ┆            ┆         │
╞═════════════╪═════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪═════════╡
│ oleo_figado ┆ 1   ┆ https://dr ┆ Oleo puro  ┆ … ┆ null       ┆ null       ┆ Revisado   ┆ null    │
│ _bacalhau   ┆     ┆ ive.google ┆ de figado  ┆   ┆            ┆            ┆            ┆         │
│             ┆     ┆ .com/file/ ┆ de         ┆   ┆            ┆            ┆            ┆         │
│             ┆     ┆ …          ┆ bacalha…   ┆   ┆            ┆            ┆            ┆         │
│ tonico_orie ┆ 2   ┆ https://dr ┆ Tonico     ┆ … ┆ null       ┆ null       ┆ Revisado   ┆ null    │
│ ntal_cabell ┆     ┆ ive.google ┆ oriental   ┆   ┆            ┆            ┆            ┆         │
│ o           ┆     ┆ .com/file/ ┆ para o     ┆   ┆            ┆            ┆            ┆         │
│             ┆     ┆ …          ┆ cabello    ┆   ┆            ┆            ┆            ┆         │
│ pilulas_veg ┆ 3   ┆ https://dr ┆ Pilulas    ┆ … ┆ null       ┆ null       ┆ Revisado   ┆ null    │
│ eates_assuc ┆     ┆ ive.google ┆ vegetaes   ┆   ┆            ┆            ┆            ┆         │
│ aradas_b…   ┆     ┆ .com/file/ ┆ assucarada ┆   ┆            ┆            ┆            ┆         │
│             ┆     ┆ …          ┆ s d…       ┆   ┆            ┆            ┆            ┆         │
│ og_novo_dep ┆ 4   ┆ https://dr ┆ Extracto   ┆ … ┆ null       ┆ novo_depur ┆ Revisado   ┆ null    │
│ urativo_ext ┆     ┆ ive.google ┆ fluido de  ┆   ┆            ┆ ativo_extr ┆            ┆         │
│ racto_sa…   ┆     ┆ .com/file/ ┆ salsaparri ┆   ┆            ┆ acto_salsa ┆            ┆         │
│             ┆     ┆ …          ┆ l…         ┆   ┆            ┆ …          ┆            ┆         │
│ salsaparril ┆ 5   ┆ https://dr ┆ Salsaparri ┆ … ┆ null       ┆ null       ┆ Revisado   ┆ null    │
│ ha_bristol  ┆     ┆ ive.google ┆ lha de     ┆   ┆            ┆            ┆            ┆         │
│             ┆     ┆ .com/file/ ┆ bristol    ┆   ┆            ┆            ┆            ┆         │
│             ┆     ┆ …          ┆            ┆   ┆            ┆            ┆            ┆         │
│ …           ┆ …   ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …       │
│ pilulas_ver ┆ 148 ┆ https://dr ┆ Pilulas    ┆ … ┆ null       ┆ null       ┆ Finalizado ┆ null    │
│ mifugas_dr_ ┆     ┆ ive.google ┆ vermifugas ┆   ┆            ┆            ┆            ┆         │
│ oliveira    ┆     ┆ .com/file/ ┆ do Dr      ┆   ┆            ┆            ┆            ┆         │
│             ┆     ┆ …          ┆ Olive…     ┆   ┆            ┆            ┆            ┆         │
│ elixir_cabo ┆ 152 ┆ https://dr ┆ Elixir do  ┆ … ┆ null       ┆ null       ┆ Finalizado ┆ null    │
│ clo         ┆     ┆ ive.google ┆ Caboclo    ┆   ┆            ┆            ┆            ┆         │
│             ┆     ┆ .com/file/ ┆            ┆   ┆            ┆            ┆            ┆         │
│             ┆     ┆ …          ┆            ┆   ┆            ┆            ┆            ┆         │
│ grageas_dep ┆ 149 ┆ https://dr ┆ Gragêas    ┆ … ┆ grageas_de ┆ null       ┆ Finalizado ┆ null    │
│ urativas_ma ┆     ┆ ive.google ┆ depurativa ┆   ┆ purativas_ ┆            ┆            ┆         │
│ ior         ┆     ┆ .com/file/ ┆ s          ┆   ┆ ioduradas_ ┆            ┆            ┆         │
│             ┆     ┆ …          ┆ iodurados  ┆   ┆ …          ┆            ┆            ┆         │
│             ┆     ┆            ┆ …          ┆   ┆            ┆            ┆            ┆         │
│ licor_centa ┆ 150 ┆ https://dr ┆ Licor de   ┆ … ┆ null       ┆ licor_cent ┆ Finalizado ┆ null    │
│ urea_2      ┆     ┆ ive.google ┆ centaurea  ┆   ┆            ┆ aurea_3    ┆            ┆         │
│             ┆     ┆ .com/file/ ┆            ┆   ┆            ┆ (https://w ┆            ┆         │
│             ┆     ┆ …          ┆            ┆   ┆            ┆ ww…        ┆            ┆         │
│ licor_centa ┆ 151 ┆ https://dr ┆ Licor de   ┆ … ┆ licor_cent ┆ null       ┆ Finalizado ┆ null    │
│ urea_3      ┆     ┆ ive.google ┆ centaurea  ┆   ┆ aurea_2    ┆            ┆            ┆         │
│             ┆     ┆ .com/file/ ┆            ┆   ┆ (https://w ┆            ┆            ┆         │
│             ┆     ┆ …          ┆            ┆   ┆ ww…        ┆            ┆            ┆         │
└─────────────┴─────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴─────────┘

In [6]:
def clean_text(text: str) -> str:
    translation_table = str.maketrans(' -çõãóéíâáú','__coaoeiaau', '().')
    return text.lower().translate(translation_table)

In [7]:
tables = {
    clean_text(col) : ad_analysis.select(['Identificador',col]).explode(col).unique().drop_nulls().rename({col:clean_text(col)})
    for col in multi_select_columns
}
tables.update(
       {
           'anuncios': ad_analysis.select(single_value_columns).with_columns(
                (pl.lit('https://drive.google.com/thumbnail?id=') + 
                 pl.col('Link').str.extract(r'([-\w]{25,})') + pl.lit('&sz=w1920')).alias('image_url')
            ),
           'original': (ad_analysis.select(['Identificador', 'Original (primeira aparição)']).unique().drop_nulls().with_columns(pl.col('Original (primeira aparição)').str.split(' ').list.get(0)))
       }
)

In [8]:
tables.keys()

dict_keys(['primeiras_palavras_do_anuncio', 'doenca_mencionada', 'tipo_de_produto', 'substancias', 'extras', 'informacoes_indicativas', 'mencoes_a_lugares', 'origem', 'responsavel_tecnico', 'palavra_chave_efeito', 'palavras_chave_produto', 'discursos_de_autoridade', 'publico_mencionado', 'detalhamento_do_efeito', 'detalhamento_forma_de_uso', 'autorizacoes', 'sinal_visual_de_autoridade', 'variacao_typeface', 'variacao_tipografica', 'alinhamento', 'diagramacao', 'hieraquia_da_informacao', 'tipificacao_da_imagem_aprox', 'elementos_de_composicao', 'anuncios', 'original'])

In [9]:
tables[clean_text('Primeiras palavras do anúncio')]

shape: (153, 2)
┌─────────────────────────────────┬───────────────────────────────┐
│ Identificador                   ┆ primeiras_palavras_do_anuncio │
│ ---                             ┆ ---                           │
│ str                             ┆ str                           │
╞═════════════════════════════════╪═══════════════════════════════╡
│ vinho_extracto_figado_bacalhao… ┆ Adjetivos do produto          │
│ tonico_por_excellencia          ┆ Adjetivos do produto          │
│ a_pomada_vaselina               ┆ Produto                       │
│ essencia_depurativa_ferruginos… ┆ Previlegio                    │
│ vinho_jurubeba                  ┆ Nome do produto               │
│ …                               ┆ …                             │
│ vinho_lacto_phosphato_cal_delg… ┆ Nome do produto               │
│ molestias_peito_hypophosphitos  ┆ [Moléstia]                    │
│ xarope_laroche_moldura4quininh… ┆ Produto                       │
│ elixir_caboclo                  ┆ Nome do produto               │
│ estomago_pilulas_digestivas     ┆ Orgão do corpo                │
└─────────────────────────────────┴───────────────────────────────┘

In [10]:
tables;

In [11]:
ad_insertions_raw = pl.read_csv(Path("../data/01_bronze/sheets_ficha_registro_veiculacoes.csv"))

In [12]:
schema_ad_insertions = ['Anúncio',
 'Ano',
 'Edição',
 'Página',
 'Coluna(s) ocupadas',
 'Número de Colunas',
 'Orientação']

In [13]:
tables.update(
    {
        'veiculacoes':(
            ad_insertions_raw
                .select(schema_ad_insertions)  
                .filter(pl.col('Anúncio').is_not_null())
                .rename({'Anúncio':'Identificador'})
                .with_columns(
                    pl.format("{}_{}", 
                              pl.col('Ano'), 
                              pl.col('Edição').cast(pl.Utf8).str.zfill(3)
                             )
                    .alias('ano_edicao')
    ))
    }
)

In [14]:
db_path = Path('../data/03_gold/monitor_campista_pharma_ads_1880_1884.db')
db_connection_string = f"sqlite:///{db_path.resolve()}"

for table_name, df in tables.items():
    df.write_database(
        table_name=table_name,
        connection=db_connection_string,
        if_table_exists="replace",
        engine='adbc'
    )

In [17]:
import duckdb

db_path = Path("../data/03_gold/monitor_campista_pharma_ads_1880_1884.duckdb")
con = duckdb.connect(str(db_path))

for table_name, df in tables.items():
    con.register("tmp_arrow", df.to_arrow())
    con.execute(f"CREATE OR REPLACE TABLE {table_name} AS SELECT * FROM tmp_arrow")
con.close()

In [18]:
tables.keys()

multi_select_columns_table = pl.concat([tables[clean_text(col)][clean_text(col)].unique().to_frame() for col in multi_select_columns], how='horizontal')
# multi_select_columns_table.write_csv('filename.csv')
multi_select_columns_table

shape: (243, 24)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ primeiras ┆ doenca_me ┆ tipo_de_p ┆ substanci ┆ … ┆ diagramac ┆ hieraquia ┆ tipificac ┆ elemento │
│ _palavras ┆ ncionada  ┆ roduto    ┆ as        ┆   ┆ ao        ┆ _da_infor ┆ ao_da_ima ┆ s_de_com │
│ _do_anunc ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ macao     ┆ gem_aprox ┆ posicao  │
│ io        ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---      │
│ ---       ┆           ┆           ┆           ┆   ┆           ┆ str       ┆ str       ┆ str      │
│ str       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Novo depu ┆ Tetano    ┆ Vermifugo ┆ Lactophos ┆ … ┆ 2 colunas ┆ Título    ┆ Pinheiro  ┆ Ornament │
│ rativo    ┆           ┆           ┆ phato de  ┆   ┆           ┆ principal ┆           ┆ o        │
│           ┆           ┆           ┆ cal       ┆   ┆           ┆           ┆           ┆          │
│ Efeito do ┆ Molestias ┆ Pó        ┆ Camomilla ┆ … ┆ Composiçã ┆ Título    ┆ Árvore    ┆ Clichê   │
│ produto   ┆ intestino ┆           ┆ composto  ┆   ┆ o         ┆ secundári ┆           ┆ (2)      │
│           ┆           ┆           ┆           ┆   ┆ dinâmica  ┆ o         ┆           ┆          │
│ Grande    ┆ Colicas   ┆ Capsula   ┆ Extracto  ┆ … ┆ 1 coluna  ┆ Subtítulo ┆ Bebê      ┆ Moldura  │
│ purificad ┆           ┆           ┆ de cevada ┆   ┆           ┆           ┆           ┆          │
│ or        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Nome do   ┆ Anginas   ┆ Tintura   ┆ Viburnina ┆ … ┆ null      ┆ Composiçã ┆ Caixa med ┆ Bigode   │
│ produto   ┆           ┆           ┆           ┆   ┆           ┆ o         ┆ icamento  ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ dinâmica  ┆           ┆          │
│ Produto   ┆ Inflamaçã ┆ Cigarro   ┆ Cognac    ┆ … ┆ null      ┆ Corpo do  ┆ Represent ┆ Clichê   │
│           ┆ o intesti ┆           ┆ velho     ┆   ┆           ┆ texto     ┆ ação do   ┆ original │
│           ┆ nal       ┆           ┆           ┆   ┆           ┆           ┆ produto   ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ null      ┆ Doença do ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ estomago  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ null      ┆ Calvice   ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ null      ┆ Tosse     ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ chronica  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ e         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ convulsa  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ null      ┆ Inappeten ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ cia       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ null      ┆ Vertigens ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘